name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - mxdvl/visualisation # for testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.15.2

      - name: Build gh-pages
        run: |
          deno --version
          deno bundle visualisation/index.js public/build/bundle.js --config=tsconfig.json

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public